[package]
name = "hydro_1d_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.22"
yaml-rust = "0.4"
clap = {version = "3.2", features = ["derive"]}
derive_more = "0.99"
meshless_voro = { git = "https://github.com/yuyttenhove/meshless_voro.git" }

[dev-dependencies]
float-cmp = "0.9"