time_integration:
  dt_min: 0.001
  dt_max: 0.008
  t_end: 10.
  sync_timesteps: true

snapshots:
  dt_snap: 1.
  prefix: advection_box_waf_vanleer
  save_faces: false

engine:
  dt_status: 10.
  particle_motion: fixed
  runner: OptimalOrder

hydrodynamics:
  solver: WAF
  equation_of_state: Ideal
  gamma: 1.66666667
  cfl_criterion: 0.8
  TVD: true
  flux_limiter: "vanleer"
  slope_limiter:
    kind: "gradients"
    beta: 1.
  riemann_solver:
    kind: "LinearAdvection"
    threshold: 2.
    velocity: [1., 0., 0.]

space:
  boundary: periodic
  max_top_level_cells: 8

initial_conditions:
  kind: file
  dimensionality: 1
  box_size: [ 2., 1., 1. ]
  num_part: 250
  perturbations: 0.0
  filename: ICs/advection_box_100.hdf5