time_integration:
  dt_min: 1e-11
  dt_max: 0.05
  t_end: 0.2
  sync_timesteps: false

snapshots:
  dt_snap: 0.01
  prefix: sodshock_1D
  save_faces: true

engine:
  dt_status: 0.
  particle_motion: fluid
  # runner: DefaultHalfDrift
  # runner: OptimalOrderHalfDrift
  # runner: TwoVolumeHalfDrift
  # runner: MeshlessGradientHalfDrift
  # runner: FluxExtrapolateHalfDrift
  runner: OptimalOrder
  # runner: TwoGradient
  # runner: Default
  # runner: Pakmor
  # runner: PakmorExtrapolate
  # runner: VolumeBackExtrapolate
gravity:
  kind: none
  potential:
    kind: constant
    acceleration: [0., -1., 0.]

hydrodynamics:
  solver: Godunov
  equation_of_state: Ideal
  gamma: 1.66666667
  cfl_criterion: 0.5
  riemann_solver:
    kind: LinearAdvection
    threshold: 2.
    velocity: [1., 0., 0.]

space:
  boundary: reflective
  max_top_level_cells: 8

initial_conditions:
  kind: sodshock
  dimensionality: 1
  box_size: [ 2., 1., 1. ]
  num_part: 1000
  perturbations: 0.0
  filename: ICs/sodshock_2D.hdf5