time_integration:
  dt_min: 1e-11
  dt_max: 0.05
  t_end: 0.2
  cfl_criterion: 0.3
  sync_timesteps: false

snapshots:
  dt_snap: 0.01
  prefix: sodshock_2D
  save_faces: true

engine:
  dt_status: 1e-3
  particle_motion: fixed
  # runner: DefaultHalfDrift
  # runner: OptimalOrderHalfDrift
  # runner: TwoVolumeHalfDrift
  # runner: MeshlessGradientHalfDrift
  # runner: FluxExtrapolateHalfDrift
  runner: OptimalOrder
  # runner: TwoGradient
  # runner: Default
  # runner: Pakmor
  # runner: PakmorExtrapolate
  # runner: VolumeBackExtrapolate
gravity:
  kind: none
  potential:
    kind: constant
    acceleration: [0., -1., 0.]

hydrodynamics:
  gamma: 1.66666667
  equation_of_state: Ideal
riemann_solver: 
  kind: AIRS
  threshold: 2.

space:
  boundary: reflective
  max_top_level_cells: 8

initial_conditions:
  kind: file
  dimensionality: 2
  box_size: [4., 1., 1.]
  num_part: 4096
  perturbations: 0.01
  filename: ICs/sodshock_2D.hdf5