time_integration:
  dt_min: 1e-11
  dt_max: 1e0
  t_min: 1e-8
  t_end: 0.5
  cfl_criterion: 3.0

snapshots:
  t_between_snaps: 0.05
  prefix: "sodshock_1D_"
  save_faces: false

engine:
  t_status: 1e-2
  particle_motion: "steer"
  # runner: "DefaultHalfDrift"
  # runner: "OptimalOrderHalfDrift"
  # runner: "TwoVolumeHalfDrift"
  # runner: "MeshlessGradientHalfDrift"
  # runner: "FluxExtrapolateHalfDrift"
  # runner: "OptimalOrder"
  # runner: "TwoGradient"
  # runner: "Default"
  # runner: "Pakmor"

gravity:
  kind: "none"
  potential:
    kind: "constant"
    acceleration: [0., -1., 0.]

hydrodynamics:
  solver: "AIRS"
  threshold: 2.

space:
  boundary: "reflective"
  max_top_level_cells: 12

initial_conditions:
  type: "sodshock"
  box_size: [2., 1., 1.]
  num_part: 250
  filename: "ICs/yee_25.hdf5"

equation_of_state:
  gamma: 1.66666667