time_integration:
  dt_min: 1e-9
  dt_max: 1e-2
  t_min: 1e-8
  t_end: 0.5
  cfl_criterion: 0.3

snapshots:
  t_between_snaps: 0.05
  prefix: "sod_shock_"

initial_conditions:
  num_part: 250
  box_size: 2.
  periodic: true

equation_of_state:
  gamma: 1.66666666667