time_integration:
  dt_min: 1e-9
  dt_max: 1e-2
  t_min: 1e-8
  t_end: 1.0
  cfl_criterion: 0.01
#   runner: "OptimalOrderHalfDrift"
#   runner: "OptimalOrder"
  runner: "Default"

snapshots:
  t_between_snaps: 0.05
  prefix: "noh_"

engine:
  t_status: 0.01

initial_conditions:
  type: "noh"
  num_part: 250
  box_size: 4.
  periodic: true

equation_of_state:
  gamma: 1.66666666667