time_integration:
  t_min: 1e-4
  t_end: 0.5
  cfl_criterion: 0.1

snapshots:
  t_between_snaps: 0.1
  prefix: "sod_shock_"

initial_conditions:
  num_part: 500
  box_size: 2.
  periodic: true

equation_of_state:
  gamma: 1.66666666667