time_integration:
  dt_min: 1e-11
  dt_max: 0.05
  t_end: 0.2
  cfl_criterion: 0.3
  sync_timesteps: true

snapshots:
  t_between_snaps: 0.02
  prefix: "sodshock_2D_two_volume_half_"
  save_faces: false

engine:
  t_status: 1e-3
  particle_motion: "steer"
  # runner: "DefaultHalfDrift"
  # runner: "OptimalOrderHalfDrift"
  runner: "TwoVolumeHalfDrift"
  # runner: "MeshlessGradientHalfDrift"
  # runner: "FluxExtrapolateHalfDrift"
  # runner: "OptimalOrder"
  # runner: "TwoGradient"
  # runner: "Default"
  # runner: "Pakmor"
  # runner: "PakmorExtrapolate"
gravity:
  kind: "none"
  potential:
    kind: "constant"
    acceleration: [0., -1., 0.]

hydrodynamics:
  solver: "AIRS"
  threshold: 2.

space:
  boundary: "reflective"
  max_top_level_cells: 12

initial_conditions:
  type: "file"
  box_size: [2., 1., 1.]
  num_part: 250
  filename: "ICs/sodshock_2D.hdf5"

equation_of_state:
  gamma: 1.66666667