time_integration:
  dt_min: 1e-11
  dt_max: 1e-2
  t_min: 1e-8
  t_end: 0.25
  cfl_criterion: 0.3

snapshots:
  t_between_snaps: 0.05
  prefix: "sodshock_2D_"

engine:
  t_status: 0.005
  particle_motion: "steer"
#   runner: "DefaultHalfDrift"
  # runner: "OptimalOrderHalfDrift"
  runner: "OptimalOrder"
  # runner: "Default"

gravity:
  kind: "none"
  potential:
    kind: "constant"
    acceleration: [0., -1., 0.]

hydrodynamics:
  solver: "AIRS"
  threshold: 2.

space:
  boundary: "reflective"

initial_conditions:
  type: "file"
  box_size: [2., 1., 1.]
  num_part: 200
  filename: "ICs/sodshock_2D.hdf5"

equation_of_state:
  gamma: 1.66666666667