time_integration:
  dt_min: 1e-11
  dt_max: 1e-2
  t_min: 1e-8
  t_end: 20.
  cfl_criterion: 0.1

snapshots:
  t_between_snaps: 1.
  prefix: "yee_25_"
  save_faces: false

engine:
  t_status: 0.1
  particle_motion: "steer"
  # runner: "DefaultHalfDrift"
  # runner: "OptimalOrderHalfDrift"
  # runner: "TwoGradientHalfDrift"
  # runner: "MeshlessGradientHalfDrift"
  # runner: "OptimalOrder"
  # runner: "TwoGradient"
  # runner: "Default"
  runner: "Pakmor"

gravity:
  kind: "none"
  potential:
    kind: "constant"
    acceleration: [0., -1., 0.]

hydrodynamics:
  solver: "HLLC"
  threshold: 2.

space:
  boundary: "reflective"
  max_top_level_cells: 12

initial_conditions:
  type: "file"
  box_size: [2., 1., 1.]
  num_part: 200
  filename: "ICs/yee_25.hdf5"

equation_of_state:
  gamma: 1.66666667