time_integration:
  dt_min: 1e-11
  dt_max: 1e-2
  t_min: 1e-8
  t_end: 0.5
  cfl_criterion: 0.05

snapshots:
  t_between_snaps: 0.05
  prefix: "noh_"

engine:
  t_status: 0.01
  solver: "HLLC"
  particle_motion: "fluid"
#   runner: "OptimalOrderHalfDrift"
  runner: "OptimalOrder"
#   runner: "Default"

space:
  box_size: 2.
  periodic: true

initial_conditions:
  type: "noh"
  num_part: 1000

equation_of_state:
  gamma: 1.66666666667